In [9]:
pip install pandas

Requirement already satisfied: pandas in ./venv/lib64/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in ./venv/lib64/python3.14/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib64/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib64/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd

# Creating series with list
l = [1,2,3,4,5]
s = pd.Series(l)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
s = pd.Series(l, index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
import numpy as np

a = np.array([10,50,20])
pd.Series(a)

0    10
1    50
2    20
dtype: int64

In [13]:
#Creating Series with Dictionary
d={'name':'miraj','roll':10,'age':15}
s=pd.Series(d)
s

name    miraj
roll       10
age        15
dtype: object

In [14]:
a = pd.Series([1,2,3])
b = pd.Series([2,3,4])
a+b # Adds elements at [index] of the series ///Doesn't concat

0    3
1    5
2    7
dtype: int64

In [20]:
#making data frame by reading excel
df=pd.read_excel(r"/home/chris/Documents/Broadway Python/Lesson 2/archive/pandas_data/excel_df.xlsx")
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [22]:
# Making data frame by reading csv
df=pd.read_csv(r"/home/chris/Documents/Broadway Python/Lesson 2/archive/pandas_data/new_data.csv")
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [51]:
dict = {'name': ['miraj', 'sabal', 'sarita', 'rashmi', 'sabnam'],
        'roll': [1, 2, 3, 4, 5], 'age': [13, 34, 32, 54, 32],}
df = pd.DataFrame(dict, index=['a','b','c','d','e'])
df

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [57]:
df.at['a', 'name']

'miraj'

In [58]:
df.at['d','name']

'rashmi'

In [59]:
df.iat[3, 0] # Row by Column

'rashmi'

In [60]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [61]:
df.axes[1]

Index(['name', 'roll', 'age'], dtype='str')

In [62]:
df.columns

Index(['name', 'roll', 'age'], dtype='str')

In [63]:
df.dtypes

name      str
roll    int64
age     int64
dtype: object

In [64]:
df['name']

a     miraj
b     sabal
c    sarita
d    rashmi
e    sabnam
Name: name, dtype: str

In [66]:
df['age'].value_counts()

age
32    2
13    1
34    1
54    1
Name: count, dtype: int64

In [67]:
df.to_dict()

{'name': {'a': 'miraj',
  'b': 'sabal',
  'c': 'sarita',
  'd': 'rashmi',
  'e': 'sabnam'},
 'roll': {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5},
 'age': {'a': 13, 'b': 34, 'c': 32, 'd': 54, 'e': 32}}

In [71]:
df.to_json('new.json', indent=4)

In [75]:
df.sort_index(ascending=False)

     name  roll  age
e  sabnam     5   32
d  rashmi     4   54
c  sarita     3   32
b   sabal     2   34
a   miraj     1   13

In [77]:
df.set_index('roll')

        name  age
roll
1      miraj   13
2      sabal   34
3     sarita   32
4     rashmi   54
5     sabnam   32

In [79]:
df.reset_index()

  index    name  roll  age
0     a   miraj     1   13
1     b   sabal     2   34
2     c  sarita     3   32
3     d  rashmi     4   54
4     e  sabnam     5   32

In [ ]:
df.reset_index(drop=True)

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [8]:
import numpy as np
import pandas as pd

data = {'Name': ['John', 'Emma', np.nan],
'Age': [25, np.nan, 30],
'Height': [175, 162, np.nan]}
df = pd.DataFrame(data)
df

   Name   Age  Height
0  John  25.0   175.0
1  Emma   NaN   162.0
2   NaN  30.0     NaN

In [11]:
df.replace(np.nan, None, inplace=True)

   Name   Age Height
0  John  25.0  175.0
1  Emma  None  162.0
2   NaN  30.0   None