In [2]:
pip install pandas

634.26s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /usr/lib64/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/lib64/python3.14/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.14/site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

# Creating series with list
l = [1, 2, 3, 4, 5]
s = pd.Series(l)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
s = pd.Series(l, index=["a", "b", "c", "d", "e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
import numpy as np

a = np.array([10, 50, 20])
pd.Series(a)

0    10
1    50
2    20
dtype: int64

In [6]:
# Creating Series with Dictionary
d = {"name": "miraj", "roll": 10, "age": 15}
s = pd.Series(d)
s

name    miraj
roll       10
age        15
dtype: object

In [7]:
a = pd.Series([1, 2, 3])
b = pd.Series([2, 3, 4])
a + b  # Adds elements at [index] of the series ///Doesn't concat

0    3
1    5
2    7
dtype: int64

In [8]:
# making data frame by reading excel
df = pd.read_excel(
    r"/home/chris/Documents/Broadway Python/Lesson 2/archive/pandas_data/excel_df.xlsx"
)
df

FileNotFoundError: [Errno 2] No such file or directory: '/home/chris/Documents/Broadway Python/Lesson 2/archive/pandas_data/excel_df.xlsx'

In [ ]:
# Making data frame by reading csv
df = pd.read_csv(
    r"/home/chris/Documents/Broadway Python/Lesson 2/archive/pandas_data/new_data.csv"
)
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [ ]:
dict = {
    "name": ["miraj", "sabal", "sarita", "rashmi", "sabnam"],
    "roll": [1, 2, 3, 4, 5],
    "age": [13, 34, 32, 54, 32],
}
df = pd.DataFrame(dict, index=["a", "b", "c", "d", "e"])
df

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [ ]:
df.at["a", "name"]

'miraj'

In [ ]:
df.at["d", "name"]

'rashmi'

In [ ]:
df.iat[3, 0]  # Row by Column

'rashmi'

In [ ]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [ ]:
df.axes[1]

Index(['name', 'roll', 'age'], dtype='str')

In [ ]:
df.columns

Index(['name', 'roll', 'age'], dtype='str')

In [ ]:
df.dtypes

name      str
roll    int64
age     int64
dtype: object

In [ ]:
df["name"]

a     miraj
b     sabal
c    sarita
d    rashmi
e    sabnam
Name: name, dtype: str

In [ ]:
df["age"].value_counts()

age
32    2
13    1
34    1
54    1
Name: count, dtype: int64

In [ ]:
df.to_dict()

{'name': {'a': 'miraj',
  'b': 'sabal',
  'c': 'sarita',
  'd': 'rashmi',
  'e': 'sabnam'},
 'roll': {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5},
 'age': {'a': 13, 'b': 34, 'c': 32, 'd': 54, 'e': 32}}

In [ ]:
df.to_json("new.json", indent=4)

In [ ]:
df.sort_index(ascending=False)

     name  roll  age
e  sabnam     5   32
d  rashmi     4   54
c  sarita     3   32
b   sabal     2   34
a   miraj     1   13

In [ ]:
df.set_index("roll")

        name  age
roll
1      miraj   13
2      sabal   34
3     sarita   32
4     rashmi   54
5     sabnam   32

In [ ]:
df.reset_index()

  index    name  roll  age
0     a   miraj     1   13
1     b   sabal     2   34
2     c  sarita     3   32
3     d  rashmi     4   54
4     e  sabnam     5   32

In [ ]:
df.reset_index(drop=True)

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [ ]:
import numpy as np
import pandas as pd

data = {
    "Name": ["John", "Emma", np.nan],
    "Age": [25, np.nan, 30],
    "Height": [175, 162, np.nan],
}
df = pd.DataFrame(data)
df

   Name   Age  Height
0  John  25.0   175.0
1  Emma   NaN   162.0
2   NaN  30.0     NaN

In [ ]:
df.replace(np.nan, None, inplace=True)

In [ ]:
df = pd.read_csv(
    r"/home/chris/Documents/Broadway Python/Lesson 1/Lesson 2/archive/student_data_english.csv",
    index_col="roll_no",
)
df

,name,address,age,gender,hobby,iq,pass_status
roll_no,,,,,,,
15,Suman,Lalitpur,24.0,Other,Reading,89.0,Fail
17,Suman,Birtamod,24.0,Other,Cricket,114.0,Pass
94,Laxmi Gurung,Rajbiraj,17.0,Male,Painting,88.0,Pass
4,Bishnu Maya,Beni,23.0,Other,Cycling,122.0,Fail
22,Bishnu Maya,Balewa,17.0,Male,Yoga,97.0,Fail
...,...,...,...,...,...,...,...
54,Deepak,Biratnagar,16.0,Other,Swimming,133.0,Pass
85,Vikas,Kathmandu,17.0,Other,Video Games,123.0,Fail
78,Narayan Gopal,Lahan,21.0,Female,Video Games,122.0,Pass
71,NaN,Baglung,16.0,Other,Playing Flute,123.0,Pass
47,NaN,Kushma,NaN,Other,Singing,86.0,Fail

In [ ]:
df.head()

                 name   address   age gender     hobby     iq pass_status
roll_no
15              Suman  Lalitpur  24.0  Other   Reading   89.0        Fail
17              Suman  Birtamod  24.0  Other   Cricket  114.0        Pass
94       Laxmi Gurung  Rajbiraj  17.0   Male  Painting   88.0        Pass
4         Bishnu Maya      Beni  23.0  Other   Cycling  122.0        Fail
22        Bishnu Maya    Balewa  17.0   Male      Yoga   97.0        Fail

In [ ]:
# we can also give index like this
df = pd.read_excel(
    r"/home/chris/Documents/Broadway Python/Lesson 1/Lesson 2/archive/pandas_data/example.xlsx"
)
df.set_index(
    "Name", inplace=True
)  # .set_index() returns new df so to modify in old data frame inplace=True
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [ ]:
name = {"info": "miraj"}

In [ ]:
df.iloc[5]

Age                      24
Roll                    106
Salary                45000
Address    987 Cedar Street
Name: Emily Davis, dtype: object

In [ ]:
# Adding column to dataframe
df["Gender"] = ["m", "f", "m", "f", "m", "f", "m", "f", "m", "f"]

In [ ]:
df

                 Age  Roll  Salary            Address Gender
Name
John Doe          27   101   50000    123 Main Street      m
Jane Smith        32   102   65000     456 Elm Avenue      f
David Johnson     41   103   80000       789 Oak Lane      m
Sarah Williams    29   104   55000      321 Pine Road      f
Michael Brown     35   105   70000    654 Maple Drive      m
Emily Davis       24   106   45000   987 Cedar Street      f
James Wilson      38   107   75000    543 Birch Court      m
Jennifer Taylor   31   108   60000    876 Walnut Lane      f
Robert Anderson   26   109   48000  234 Spruce Avenue      m
Jessica Thomas    33   110   68000    567 Cherry Lane      f

In [ ]:
df["rollAge"] = df["Roll"] + df["Age"]
df["rollAge"]

Name
John Doe           128
Jane Smith         134
David Johnson      144
Sarah Williams     133
Michael Brown      140
Emily Davis        130
James Wilson       145
Jennifer Taylor    139
Robert Anderson    135
Jessica Thomas     143
Name: rollAge, dtype: int64

In [ ]:
df

                 Age  Roll  Salary            Address Gender  rollAge
Name
John Doe          27   101   50000    123 Main Street      m      128
Jane Smith        32   102   65000     456 Elm Avenue      f      134
David Johnson     41   103   80000       789 Oak Lane      m      144
Sarah Williams    29   104   55000      321 Pine Road      f      133
Michael Brown     35   105   70000    654 Maple Drive      m      140
Emily Davis       24   106   45000   987 Cedar Street      f      130
James Wilson      38   107   75000    543 Birch Court      m      145
Jennifer Taylor   31   108   60000    876 Walnut Lane      f      139
Robert Anderson   26   109   48000  234 Spruce Avenue      m      135
Jessica Thomas    33   110   68000    567 Cherry Lane      f      143

In [ ]:
df.drop(columns="rollAge", inplace=True)
df

                 Age  Roll  Salary            Address Gender
Name
John Doe          27   101   50000    123 Main Street      m
Jane Smith        32   102   65000     456 Elm Avenue      f
David Johnson     41   103   80000       789 Oak Lane      m
Sarah Williams    29   104   55000      321 Pine Road      f
Michael Brown     35   105   70000    654 Maple Drive      m
Emily Davis       24   106   45000   987 Cedar Street      f
James Wilson      38   107   75000    543 Birch Court      m
Jennifer Taylor   31   108   60000    876 Walnut Lane      f
Robert Anderson   26   109   48000  234 Spruce Avenue      m
Jessica Thomas    33   110   68000    567 Cherry Lane      f

In [ ]:
# Adding multiple Colums in data frame
df[["Height", "Weight"]] = [
    ["5ft", "1kg"],
    ["5.5ft", "2kg"],
    ["6ft", "33kg"],
    ["7ft", "43kg"],
    ["4ft", "34kg"],
    ["4ft", "56kg"],
    ["3ft", "45kg"],
    ["5ft", "76kg"],
    ["4.5ft", "78kg"],
    ["6ft", "90kg"],
]
df

                 Age  Roll  Salary            Address Gender Height Weight
Name
John Doe          27   101   50000    123 Main Street      m    5ft    1kg
Jane Smith        32   102   65000     456 Elm Avenue      f  5.5ft    2kg
David Johnson     41   103   80000       789 Oak Lane      m    6ft   33kg
Sarah Williams    29   104   55000      321 Pine Road      f    7ft   43kg
Michael Brown     35   105   70000    654 Maple Drive      m    4ft   34kg
Emily Davis       24   106   45000   987 Cedar Street      f    4ft   56kg
James Wilson      38   107   75000    543 Birch Court      m    3ft   45kg
Jennifer Taylor   31   108   60000    876 Walnut Lane      f    5ft   76kg
Robert Anderson   26   109   48000  234 Spruce Avenue      m  4.5ft   78kg
Jessica Thomas    33   110   68000    567 Cherry Lane      f    6ft   90kg

In [ ]:
df.drop(columns=["Height", "Gender", "Weight"], inplace=True)
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

## loc and iloc

In [ ]:
df = pd.read_excel(
    r"/home/chris/Documents/Broadway Python/Lesson 1/Lesson 2/archive/pandas_data/example.xlsx",
    index_col="Name",
)
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [ ]:
df.loc["Jessica Thomas"]

Age                     33
Roll                   110
Salary               68000
Address    567 Cherry Lane
Name: Jessica Thomas, dtype: object

In [ ]:
df.query("Age > 30")

                 Age  Roll  Salary          Address
Name
Jane Smith        32   102   65000   456 Elm Avenue
David Johnson     41   103   80000     789 Oak Lane
Michael Brown     35   105   70000  654 Maple Drive
James Wilson      38   107   75000  543 Birch Court
Jennifer Taylor   31   108   60000  876 Walnut Lane
Jessica Thomas    33   110   68000  567 Cherry Lane

In [ ]:
df["Address"] == "456 Elm Avenue"

Name
John Doe           False
Jane Smith          True
David Johnson      False
Sarah Williams     False
Michael Brown      False
Emily Davis        False
James Wilson       False
Jennifer Taylor    False
Robert Anderson    False
Jessica Thomas     False
Name: Address, dtype: bool

In [ ]:
df[df["Address"] == "456 Elm Avenue"]

            Age  Roll  Salary         Address
Name
Jane Smith   32   102   65000  456 Elm Avenue

#### Sytnax for loc
df.loc[row, column]

In [ ]:
df.loc["John Doe", "Salary"]

np.int64(50000)

In [ ]:
# For retrieving more than one value of a row
df.loc["John Doe", ["Age", "Salary"]]

Age          27
Salary    50000
Name: John Doe, dtype: object

In [ ]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [ ]:
df.loc[
    "David Johnson":"Jennifer Taylor"
]  # The df['Address'] == '456 Elm Avenue'last index is inclusive here.

                 Age  Roll  Salary           Address
Name
David Johnson     41   103   80000      789 Oak Lane
Sarah Williams    29   104   55000     321 Pine Road
Michael Brown     35   105   70000   654 Maple Drive
Emily Davis       24   106   45000  987 Cedar Street
James Wilson      38   107   75000   543 Birch Court
Jennifer Taylor   31   108   60000   876 Walnut Lane

In [ ]:
df.loc[
    "David Johnson":"Jennifer Taylor":2, "Age":"Address":2
]  # You can either using slicing of big brackets method here to retrieve columns

               Age  Salary
Name
David Johnson   41   80000
Michael Brown   35   70000
James Wilson    38   75000

In [ ]:
df.iloc[3:5, 1]  # 1=Roll, Name isn't column 0 here, Age is column 0

Name
Sarah Williams    104
Michael Brown     105
Name: Roll, dtype: int64

In [ ]:
filtered = df[(df["Salary"] > 45000) & (df["Salary"] < 60000)]
filtered

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Sarah Williams    29   104   55000      321 Pine Road
Robert Anderson   26   109   48000  234 Spruce Avenue

In [ ]:
filtered["Salary"].mean()

np.float64(51000.0)

In [ ]:
df.loc["John Doe", "Salary"] = 60000
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   60000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        "SN": [1.0, 2.0, 3.0, 4.0, np.nan, 6.0],
        "Age": [32, 5, 42, 37, 29, 31],
        "Roll": ["A01", "B07", "C03", np.nan, "E05", "F08"],
        "Employee ID": [100234.0, 102345.0, 105678.0, 107890.0, 109876.0, np.nan],
        "Name": [
            np.nan,
            "Jane Smith",
            "David Brown",
            "Lisa Green",
            "Mark Davis",
            "Anna",
        ],
    }
)

df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

In [ ]:
df.isnull()

      SN    Age   Roll  Employee ID   Name
0  False  False  False        False   True
1  False  False  False        False  False
2  False  False  False        False  False
3  False  False   True        False  False
4   True  False  False        False  False
5  False  False  False         True  False

In [ ]:
df[
    df.isnull().any(axis=1)
]  # axis=1 means check for null values in rows, axis=0 means check for null values in columns

    SN  Age Roll  Employee ID        Name
0  1.0   32  A01     100234.0         NaN
3  4.0   37  NaN     107890.0  Lisa Green
4  NaN   29  E05     109876.0  Mark Davis
5  6.0   31  F08          NaN        Anna

In [ ]:
df[df["SN"].isnull()]

   SN  Age Roll  Employee ID        Name
4 NaN   29  E05     109876.0  Mark Davis

In [ ]:
df.isnull().sum()

SN             1
Age            0
Roll           1
Employee ID    1
Name           1
dtype: int64

In [ ]:
df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

In [ ]:
df[
    df.isnull().any(axis=1)
]  # axis=1 means check for null values in rows, axis=0 means check for null values in columns

    SN  Age Roll  Employee ID        Name
0  1.0   32  A01     100234.0         NaN
3  4.0   37  NaN     107890.0  Lisa Green
4  NaN   29  E05     109876.0  Mark Davis
5  6.0   31  F08          NaN        Anna

In [ ]:
df.dropna()

    SN  Age Roll  Employee ID         Name
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown

In [ ]:
df["Name"].dropna()

1     Jane Smith
2    David Brown
3     Lisa Green
4     Mark Davis
5           Anna
Name: Name, dtype: object

In [ ]:
df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

## Handling duplicated values

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'SN': [1, 2, 3, 4, 2, 6, 4],
    'Age': [32, 5, 42, 34, 5, 31, 34],
    'Roll': ['A01', 'B07', 'C03', 'df4', 'B07', 'F08', 'df4'],
    'Employee ID': [100234.0, 102345.0, 105678.0, 23242.0, 102345.0, np.nan, 23242.0],
    'Name': ['mmd', 'Jane Smith', 'David Brown', 'miraj', 'Jane Smith', 'Anna', 'miraj']
})

df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
4   2    5  B07     102345.0   Jane Smith
5   6   31  F08          NaN         Anna
6   4   34  df4      23242.0        miraj

In [10]:
df[df.duplicated()]

   SN  Age Roll  Employee ID        Name
4   2    5  B07     102345.0  Jane Smith
6   4   34  df4      23242.0       miraj

In [13]:
df.drop_duplicates(inplace=True)
df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
5   6   31  F08          NaN         Anna

In [ ]:
~df.duplicated() #Where there are no duplicates, it will return True, and where there are duplicates, it will return False.

0    True
1    True
2    True
3    True
5    True
dtype: bool

In [15]:
df.nunique()

SN             5
Age            5
Roll           5
Employee ID    4
Name           5
dtype: int64

In [16]:
df['Name'] == "miraj"

0    False
1    False
2    False
3     True
5    False
Name: Name, dtype: bool

In [29]:
df.iloc[3]

SN                   4
Age                 34
Roll               df4
Employee ID    23242.0
Name             miraj
Name: 3, dtype: object

In [27]:
df.loc[3]

SN                   4
Age                 34
Roll               df4
Employee ID    23242.0
Name             miraj
Name: 3, dtype: object

In [30]:
df.iloc[3].reset_index()

         index        3
0           SN        4
1          Age       34
2         Roll      df4
3  Employee ID  23242.0
4         Name    miraj

In [31]:
df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
5   6   31  F08          NaN         Anna

In [37]:
df.query("Name == 'miraj'")

   SN  Age Roll  Employee ID   Name
3   4   34  df4      23242.0  miraj